In [2]:
import numpy as np

In [6]:
arr = np.random.randint(100, size=6)

In [7]:
arr

array([83, 21, 36, 87, 70, 88])

In [8]:
# Filtering
# Remove everything less than 50

filt_arr = np.where(arr >= 50, arr, 0)

In [9]:
filt_arr

array([83,  0,  0, 87, 70, 88])

In [22]:
# Adding based on true/false

initial_arr = [True, False]
bool_arr = np.random.choice(initial_arr, size=6)
bool_arr

array([False,  True, False, False,  True,  True])

In [23]:
high_arr = np.where(bool_arr, filt_arr + 20, filt_arr)
high_arr

array([ 83,  20,   0,  87,  90, 108])

In [24]:
# Reshaping

high_arr.shape

(6,)

In [35]:
shaped_arr = high_arr.reshape(6,1)
shaped_arr

array([[ 83],
       [ 20],
       [  0],
       [ 87],
       [ 90],
       [108]])

In [34]:
# Go back

shaped_arr2 = high_arr.reshape(6,)
shaped_arr2

array([ 83,  20,   0,  87,  90, 108])

In [76]:
# Restructuring

matrix = np.array([[1, 2], [3, 4], [5, 6]])
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [81]:
restr_matrix = np.moveaxis(matrix, [0,1], [1,0])
restr_matrix

array([[1, 3, 5],
       [2, 4, 6]])

In [79]:
# Compare

reshaped_matrix = matrix.reshape(2,3)
reshaped_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
# Unique values

flavours = np.array(['Chocolate', 'Vanilla', 'Strawberry', 'Vanilla', 'Mint', 'Chocolate'])
unique_flavours = np.unique(flavours)
unique_flavours_cnt = np.unique(flavours, return_counts = True)
unique_flavours
unique_flavours_cnt

(array(['Chocolate', 'Mint', 'Strawberry', 'Vanilla'], dtype='<U10'),
 array([2, 1, 1, 2], dtype=int64))

In [98]:
# Combining arrays

arr1 = np.arange(10)
arr2 = np.arange(10,20)
new_arr = np.concatenate((arr1, arr2))
new_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [100]:
# Stacking arrays

arr1 = arr1.reshape(10,1)
arr2 = arr2.reshape(10,1)
stacked_arr = np.concatenate((arr1, arr2), axis = 1)
stacked_arr

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [104]:
stacked_arr = np.moveaxis(stacked_arr, [0,1], [1,0])
stacked_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [3]:
# Stacking

x = np.array([12, 95, 65])
y = np.array([30, 9, 67])
z = np.vstack((x, y))
z

array([[12, 95, 65],
       [30,  9, 67]])

In [4]:
r = np.hstack((x, y))
r

array([12, 95, 65, 30,  9, 67])

In [6]:
# Splitting

a = np.array([[12, 95, 65], [30,  9, 67]])
vsplit_a = np.vsplit(a, 2)
vsplit_a

[array([[12, 95, 65]]), array([[30,  9, 67]])]

In [9]:
hsplit_a = np.hsplit(a, 3)
hsplit_a

[array([[12],
        [30]]),
 array([[95],
        [ 9]]),
 array([[65],
        [67]])]